version: "3.3"
services:
    npm:
        image: node:alpine
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: ["npm"]
    npx:
        image: node:alpine
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: ["npx"]
volumes:
    data:
        driver: local
networks:
    default:
        external:
            name: countries-api_api_network
