/* eslint-disable @typescript-eslint/no-var-requires */

const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');

const env = require('dotenv').config().parsed;

module.exports = {
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.jsx'],
  },
  module: {
    rules: [
      {
        test: /\.(j|t)sx?$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            cacheDirectory: true,
          },
        },
      },
    ],
  },
  plugins: [
    // Simplifies creation of HTML files to serve webpack bundles.
    new HtmlWebpackPlugin({
      title: 'Countries Charts',
      inject: true, // Inject all files generated by webpack
      template: './src/index.html',
    }),

    // The EnvironmentPlugin accepts either an array of keys or an object
    // mapping its keys to their default values.
    new webpack.EnvironmentPlugin(env),
  ],
  performance: {
    hints: false,
  },
};
