#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [[ ! $(cat /proc/1/sched | head -n 1 | grep init) ]]; then {
    # If the user is committing inside the docker container
    ./node_modules/.bin/lint-staged
} else {
    # If the user is committing on their local machine
    ./app lint-staged
} fi
